# yaml-language-server: $schema=https://json.schemastore.org/grafana-provisioning.json
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus_ds_aws
    # Endpoint interno en AWS ECS vía Service Discovery
    url: http://prometheus.local:9090
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST