FROM grafana/grafana:latest

# Crear carpetas necesarias
USER root
RUN mkdir -p /etc/grafana/provisioning/dashboards/definitions

# Copiar configuraciones y asegurar permisos para el usuario grafana (472)
COPY monitoring/grafana-provisioning/datasources/ /etc/grafana/provisioning/datasources/
COPY monitoring/grafana-provisioning/dashboards/dashboard-config.yaml /etc/grafana/provisioning/dashboards/
COPY monitoring/grafana-provisioning/dashboards/*.json /etc/grafana/provisioning/dashboards/definitions/

RUN chown -R 472:472 /etc/grafana/provisioning/

USER 472

EXPOSE 3000