{
 "title": "HTTP Application Metrics",
 "tags": [
  "devops",
  "fastapi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests Total (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{route=~\"/health|/metrics|/info|/echo|/service-status\"}[5m])) by (route, method)"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status_code) (http_requests_total)"
    }
   ]
  },
  {
   "title": "Latencia P95 (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}