{
 "title": "Global Application Telemetry",
 "tags": [
  "aws",
  "telemetry",
  "fastapi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Service Health (UP)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(up{job=\"devops-app\"})"
    }
   ]
  },
  {
   "title": "Total Traffic (Last 24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{route=~\"/health|/metrics|/api/info|/api/echo|/api/status/service-status\"}[24h]))"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket{route=~\"/health|/metrics|/api/info|/api/echo|/api/status/service-status\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"4..|5..\", route=~\"/health|/metrics|/api/info|/api/echo|/api/status/service-status\"}[5m])) / sum(rate(http_requests_total{route=~\"/health|/metrics|/api/info|/api/echo|/api/status/service-status\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Requests per Second (RPS) by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (route, method) (rate(http_requests_total{route=~\"/health|/metrics|/api/info|/api/echo|/api/status/service-status\"}[5m]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Response Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (status_code) (http_requests_total{route=~\"/health|/metrics|/api/info|/api/echo|/api/status/service-status\"})",
     "legendFormat": "Status {{status_code}}"
    }
   ]
  }
 ]
}